src/java/ManageBeans/AccountsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.account.AccountManagerLocal;
import JPA.EUser;
import JPA.UserStatusEnum;
import JPA.UserTypeEnum;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Dav__
 */
@Named(value = "accountsController")
@SessionScoped
public class AccountsController implements Serializable{
    
    private Integer offset = 0;
    private Integer numResults = 0;
    
    private Long userId;
    private EUser user;
    
    private static Map<UserStatusEnum,UserStatusEnum> userStatusValues;
    static {
        userStatusValues = new LinkedHashMap<>();
        userStatusValues.put(UserStatusEnum.ACTIVE, UserStatusEnum.ACTIVE);
        userStatusValues.put(UserStatusEnum.BLOCKED, UserStatusEnum.BLOCKED);
        userStatusValues.put(UserStatusEnum.INACTIVE, UserStatusEnum.INACTIVE);
        userStatusValues.put(UserStatusEnum.TOBEAPROVED, UserStatusEnum.TOBEAPROVED);
    }
    
    private static Map<UserTypeEnum,UserTypeEnum> userTypeValues;
    static {
        userTypeValues = new LinkedHashMap<>();
        userTypeValues.put(UserTypeEnum.ADMIN, UserTypeEnum.ADMIN);
        userTypeValues.put(UserTypeEnum.NORMAL, UserTypeEnum.NORMAL);
    }
    
    @Inject
    UserController userController;
    
    @Inject
    NotificationsController notificationsController;
    
    @EJB
    AccountManagerLocal accountManager;
    
    public AccountsController() {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String o = params.get("offset");
        
        if(o != null){
            offset = Integer.parseInt(o);
        }else{
            offset = 0;
        }
        
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getNumResults() {
        return numResults;
    }

    public void setNumResults(Integer numResults) {
        this.numResults = numResults;
    }

    public EUser getUser() {
        return user;
    }

    public void setUser(EUser user) {
        this.user = user;
    }
    
    public String getName(){
        return user.getName();
    }
    
    public void setName(String name){
        user.setName(name);
    }
    
    public String getUsername(){
        return user.getUsername();
    }
    
    public void setUsername(String username){
        user.setUsername(username);
    }
    
    public String getAddress(){
        return user.getAddress();
    }
    
    public void setAddress(String address){
        user.setAddress(address);
    }
    
    public UserTypeEnum getUserType(){
        return user.getUser_type();
    }
    
    public void setUserType(UserTypeEnum userType){
        user.setUser_type(userType);
    }
    
    public UserStatusEnum getUserStatus(){
        return user.getStatus();
    }
    
    public void setUserStatus(UserStatusEnum status){
        user.setStatus(status);
    }
    
    public Float getMoney(){
        return user.getMoney();
    }
    
    public void setMoney(Float money){
        user.setMoney(money);
    }

    public Map<UserStatusEnum, UserStatusEnum> getUserStatusValues() {
        return userStatusValues;
    }

    public Map<UserTypeEnum, UserTypeEnum> getUserTypeValues() {
        return userTypeValues;
    }
    
    public List<EUser> getAllUsers(){
        
        if(offset == null || offset < 0){
            offset = 0;
        }
        
        if(userController.getLoggedUserType() == UserTypeEnum.ADMIN){
            List<EUser> results = accountManager.getAllUsers(offset);
            numResults = results.size();
            return results;
        }
        
        return null;
    }
    
    public String findUserAccount(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id != null){
            userId = Long.parseLong(id);
            user = accountManager.getUserById(userId);
            return null;
        }
        
        return "/index";
    }
    
    public String saveUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            if(accountManager.updateUser(user) != null){
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Alterações guardadas!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        return null;
    }
    
    public String blockAccount(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            if(accountManager.blockAccount(user.getId())){
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Utilziador bloqueado com sucesso!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        return "/admin/accounts";
    }
    
    public String reactivateAccount(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            if(accountManager.reactivateAccount(user.getId())){
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Utilziador reativado com sucesso!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        return "/admin/accounts";
    }
    
    public String reportUser(){
        
        return null;
    }
    
}

src/java/ManageBeans/ItemsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.auctions.AuctionsManagerLocal;
import EJB.auctions.ItemCategoriesManagerLocal;
import EJB.auctions.ItemsManagerLocal;
import JPA.EBid;
import JPA.EItem;
import JPA.EItemCategorie;
import JPA.ItemStatusEnum;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.NormalScope;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;
import javax.resource.spi.EISSystemException;

/**
 *
 * @author Dav__
 */
@Named(value = "itemsController")
@SessionScoped
public class ItemsController implements Serializable{

    private Integer offset = 0;
    private Integer numResults = 0;
    
    private EItem item;
    
    private String name;
    private String description;
    private Float initial_price;
    private Float buy_price;
    private Date limit_date;
    private ItemStatusEnum status;
    private Long categorieId;
    
    private Float bid_value;
    
    private static Map<ItemStatusEnum,ItemStatusEnum> itemStatusValues;
    static {
        itemStatusValues = new LinkedHashMap<>();
        itemStatusValues.put(ItemStatusEnum.ONBIDDING, ItemStatusEnum.ONBIDDING);
        itemStatusValues.put(ItemStatusEnum.SOLD, ItemStatusEnum.SOLD);
        itemStatusValues.put(ItemStatusEnum.TIMEOVER, ItemStatusEnum.TIMEOVER);
        itemStatusValues.put(ItemStatusEnum.CANCELED, ItemStatusEnum.CANCELED);
    }
    
    @Inject
    UserController userController;
    
    @EJB
    ItemsManagerLocal itemsManager;
    
    @EJB
    ItemCategoriesManagerLocal itemCategoriesManager;
    
    @EJB
    AuctionsManagerLocal auctionsManager;
    
    public ItemsController() {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String o = params.get("offset");
        
        if(o != null){
            offset = Integer.parseInt(o);
        }else{
            offset = 0;
        }
        
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getNumResults() {
        return numResults;
    }

    public void setNumResults(Integer numResults) {
        this.numResults = numResults;
    }
    
    public Long getItemId(){
        return item.getId();
    }

    public String getItemName() {
        return item.getName();
    }

    public void setItemName(String name) {
        item.setName(name);
    }

    public String getItemDescription() {
        return item.getDescription();
    }

    public void setItemDescription(String description) {
        item.setDescription(description);
    }

    public Float getItemInitial_price() {
        return item.getPrice_initial();
    }

    public void setItemInitial_price(Float initial_price) {
        item.setPrice_initial(initial_price);
    }

    public Float getItemBuy_price() {
        return item.getPrice_buy();
    }

    public void setItemBuy_price(Float buy_price) {
        item.setPrice_buy(buy_price);
    }

    public String getItemLimit_date() {
        return item.getDate_max_bids();
    }
    
    public String getItemOwnerName(){
        return item.getOwner().getName();
    }
    
    public Long getItemOwnerId(){
        return item.getOwner().getId();
    }

    public void setItemLimit_date(String limit_date) {
        FacesContext context = FacesContext.getCurrentInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(limit_date);
        } catch (ParseException ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!", ""));
        }
        item.setDate_max_bids(d);
    }

    public ItemStatusEnum getItemStatus() {
        return item.getStatus();
    }

    public void setItemStatus(ItemStatusEnum status) {
        item.setStatus(status);
    }

    public Long getItemCategorie() {
        return item.getCategorieId().getId();
    }
    
    public String getItemCategorieName() {
        return item.getCategorieId().getName();
    }
    
    public List<EBid> getItemBidsCollection() {
        return (List<EBid>) item.getBidsCollection();
    }

    public void setItemCategorie(Long categorieId) {
        FacesContext context = FacesContext.getCurrentInstance();
        EItemCategorie categorie = null;
        try {
            categorie = itemCategoriesManager.findCategorieById(categorieId);
        } catch (Error400Exception ex) {
            Logger.getLogger(ItemsController.class.getName()).log(Level.SEVERE, null, ex);
        }
        item.setCategorieId(categorie);
    }

    public Map<ItemStatusEnum, ItemStatusEnum> getItemStatusValues() {
        return itemStatusValues;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getInitial_price() {
        return initial_price;
    }

    public void setInitial_price(Float initial_price) {
        this.initial_price = initial_price;
    }

    public Float getBuy_price() {
        return buy_price;
    }

    public void setBuy_price(Float buy_price) {
        this.buy_price = buy_price;
    }

    public String getLimit_date() {
        if(limit_date != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            return sdf.format(limit_date);
        }
        
        return null;
    }

    public void setLimit_date(String limit_date) {
        FacesContext context = FacesContext.getCurrentInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(limit_date);
        } catch (ParseException ex) {
            //Logger.getLogger(ItemsController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!", ""));
        }
        this.limit_date = d;
    }

    public ItemStatusEnum getStatus() {
        return status;
    }

    public void setStatus(ItemStatusEnum status) {
        this.status = status;
    }

    public Long getCategorieId() {
        return categorieId;
    }

    public void setCategorieId(Long categorieId) {
        this.categorieId = categorieId;
    }

    public Float getBid_value() {
        return bid_value;
    }

    public void setBid_value(Float bid_value) {
        this.bid_value = bid_value;
    }

    
    public void validateDate(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(valor.toString());
        } catch (ParseException ex) {
            FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!!", ""); 
            throw new ValidatorException(fmsg);
        }
        
    }
    
    public void validateBidValue(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        Float value = (Float) valor;
        
        List<EBid> bids = getItemBidsCollection();
        
        if(bids != null && bids.size() > 0 ){
            if(bids.get(0).getBid_value() >= value){
                FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "A bid tem que ser superior ao último valor!!", ""); 
                throw new ValidatorException(fmsg);
            }
        }else{
            if(item.getPrice_initial() >= value){
                FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "A bid tem que ser superior ao valor inicial!!", ""); 
                throw new ValidatorException(fmsg);
            }
        }
    }
    
    public String findItem(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id!=null){
            try {
                item = itemsManager.findItembyId(Long.parseLong(id));
            } catch (Error400Exception ex) {
                //Logger.getLogger(ItemCategoriesController.class.getName()).log(Level.SEVERE, null, ex);
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
            }
        }
        
        return null;
    }
    
    public String findItemOwnedByUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id!=null){
            try {
                item = itemsManager.findItemByIdByUser(Long.parseLong(id), userController.getLoggedUser().getId());
                
                if(item == null){

web/admin/accounts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <f:metadata >
        <f:viewAction action="#{userController.validateAdminPermissions}" />
    </f:metadata>
    
    <ui:define name="content">
        
        <h:panelGroup layout="block" class="col-md-12">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Contas de Utilizadores</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    <h:dataTable value="#{accountsController.allUsers}" var="item" cellpadding="0" cellspacing="0"
                                 rules="all" class="table table-responsive table-hover" >
                        
                        <h:column  >
                           <f:facet name="header">
                               <h:outputText value="Nome"/>
                           </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </h:column>
                        <h:column >
                           <f:facet name="header">
                               <h:outputText value="Username"/>
                           </f:facet>
                            <h:outputText value="#{item.username}"/>
                        </h:column>
                        <h:column >
                           <f:facet name="header">
                               <h:outputText value="Estado"/>
                           </f:facet>
                           <h:outputText value="#{item.status}"/>
                        </h:column>
                        <h:column >
                           <f:facet name="header">
                               <h:outputText value="Ações"/>
                           </f:facet>
                                
                            <h:link class="btn btn-default" style="float: right" outcome="/admin/user?id=#{item.id}">
                                <h:panelGroup class="glyphicon glyphicon-user"  ></h:panelGroup>
                            </h:link>
  
                       </h:column>
                        
                    </h:dataTable>
                    
                    <h:panelGroup layout="block" class="col-md-12" >
                        
                        <h:form>
                            
                            <h:link style="float: left" rendered="#{accountsController.offset ge 10}" outcome="/admin/accounts?offset=#{accountsController.offset - 10}">
                                <h:panelGroup class="glyphicon glyphicon-chevron-left"></h:panelGroup> Anterior
                            </h:link>
                            
                            <h:link style="float: right" rendered="#{accountsController.numResults eq 10}" outcome="/admin/accounts?offset=#{accountsController.offset + 10}">
                                Próximo <h:panelGroup class="glyphicon glyphicon-chevron-right"></h:panelGroup>
                            </h:link>
                            
                        </h:form>
                        
                    </h:panelGroup>
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
    </ui:define>


</ui:composition>

web/admin/item.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <f:metadata >
        <f:viewAction action="#{userController.validateAdminPermissions}" />
        <f:viewAction action="#{itemsController.findItem}" />
    </f:metadata>
    
    <ui:define name="content">
        
        <h:panelGroup layout="block" class="col-md-12">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Item #{itemsController.itemName}</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    
                    <h:form >
                        <h:panelGroup layout="block" class="col-md-6">
                            <h:outputLabel value="Name" for="name" />
                            <h:inputText id="name" class="form-control my-input" required="true" value="#{itemsController.itemName}" requiredMessage="Introduza o nome do item!" />
                            <h:messages for="name" class="my-message-list error-list"  />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-3">
                            <h:outputLabel value="Categoria" for="categorie" />
                            <h:selectOneMenu id="categorie" class="form-control my-input"  value="#{itemsController.itemCategorie}" required="true">
                                <f:selectItems value="#{itemsController.allCategories}" />
                            </h:selectOneMenu>
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-3">
                            <h:outputLabel value="Data Limite (yyyy/mm/dd)" for="limit_date" />
                            <h:inputText id="limit_date" validator="#{itemsController.validateDate}" class="form-control my-input" required="true" value="#{itemsController.itemLimit_date}" requiredMessage="Introduza a data limite de compra de compra do item!" />
                            <h:messages for="limit_date" class="my-message-list error-list"  />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-4">
                            <h:outputLabel value="Preço inicial:" for="init_price" />
                            <h:inputText id="init_price" class="form-control my-input" required="true" value="#{itemsController.itemInitial_price}" requiredMessage="Introduza o preço inicial do item!" />
                            <h:messages for="init_price" class="my-message-list error-list"  />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-4">
                            <h:outputLabel value="Preço de Compra" for="buy_price" />
                            <h:inputText id="buy_price" class="form-control my-input" required="true" value="#{itemsController.itemBuy_price}" requiredMessage="Introduza o preço de compra do item!" />
                            <h:messages for="buy_price" class="my-message-list error-list"  />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                            <h:outputLabel value="Estado:" for="status" />
                            <h:outputText value="&nbsp;#{itemsController.itemStatus}" />
                        </h:panelGroup>
 
                        <h:panelGroup layout="block" class="col-md-9">
                            <h:outputLabel value="Descrição" for="description" />
                            <h:inputText id="description"  class="form-control my-input" value="#{itemsController.itemDescription}" />
                        </h:panelGroup>

                        
                        <h:panelGroup layout="block" class="col-md-12">
                            <h:commandButton rendered="#{itemsController.itemStatus eq 'ONBIDDING'}"
                                             class="btn btn-warning" style="float: left" action="#{itemsController.cancelItem}" value="Cancelar Item"/>
                            <h:commandButton rendered="#{itemsController.itemStatus eq 'CANCELED'}"
                                             class="btn btn-warning" style="float: left" action="#{itemsController.reactivateItem}" value="Reativar Item"/>
                            <h:commandButton class="btn btn-success" style="float: right" action="#{itemsController.saveItem}" value="Guardar" />
                        </h:panelGroup>
                    </h:form>
                    
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
    </ui:define>

</ui:composition>

web/admin/user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <f:metadata >
        <f:viewAction action="#{userController.validateAdminPermissions}" />
        <f:viewAction action="#{accountsController.findUserAccount}" />
    </f:metadata>
    
    <ui:define name="content">
        
        <h:panelGroup layout="block" class="col-md-12">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Utilizador #{accountsController.name}</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    
                    <h:form >
                        <h:panelGroup layout="block" class="col-md-9">
                            <h:outputLabel value="Name" for="name" />
                            <h:inputText id="name" class="form-control my-input" required="true" value="#{accountsController.name}" requiredMessage="Introduza o nome do utilizador!" />
                            <h:messages for="name" class="my-message-list error-list"  />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-3">
                            <h:outputLabel value="Username" for="username" />
                            <h:inputText id="username"  class="form-control my-input" required="true" value="#{accountsController.username}" requiredMessage="Introduza o username!" />
                            <h:messages for="username" class="my-message-list error-list"  />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-9">
                            <h:outputLabel value="Morada" for="address" />
                            <h:inputText id="address" class="form-control my-input" value="#{accountsController.address}" />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-3">
                            <h:outputLabel value="Dinheiro" for="money" />
                            <h:inputText id="money" class="form-control my-input" value="#{accountsController.money}" />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-6">
                            <h:outputLabel value="Tipo de utilizador" for="type" />
                            <h:selectOneMenu id="type" class="form-control my-input" value="#{accountsController.userType}" required="true">
                                <f:selectItems value="#{accountsController.userTypeValues}" />
                            </h:selectOneMenu>
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-6" style="margin-bottom: 5px">
                            <h:outputLabel value="Estado da conta:" for="status" /> 
                            <h:outputText value="&nbsp;#{accountsController.userStatus}" />
                        </h:panelGroup>
                        
                        <h:panelGroup layout="block" class="col-md-12">
                            
                            <!--<h:commandButton rendered="#{accountsController.userStatus eq 'TOBEAPROVED'}"
                                             class="btn btn-warning" style="float: left; margin-right: 10px" action="#" value="Aceitar Pedido" />
                            
                            <h:commandButton rendered="#{accountsController.userStatus eq 'TOBEAPROVED'}"
                                             class="btn btn-warning" style="float: left" action="#" value="Rejeitar Pedido" />-->
                            
                            <h:commandButton rendered="#{accountsController.userStatus eq 'BLOCKED' or accountsController.userStatus eq 'INACTIVE'}"
                                             class="btn btn-warning" style="float: left" action="#{accountsController.reactivateAccount}" value="Ativar Conta" />
                            
                            <h:commandButton rendered="#{accountsController.userStatus eq 'ACTIVE'}" 
                                             class="btn btn-warning" style="float: left" action="#{accountsController.blockAccount}" value="Suspender Conta" />

                            <h:commandButton class="btn btn-success" style="float: right" action="#{accountsController.saveUser}" value="Guardar" />
                        </h:panelGroup>
                    </h:form>
                    
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
    </ui:define>

</ui:composition>