src/java/ManageBeans/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.Exceptions.Error401Exception;
import EJB.Exceptions.Error403Exception;
import EJB.account.AccountManagerLocal;
import JPA.UserTypeEnum;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import JPA.EUser;
import JPA.UserStatusEnum;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

/**
 *
 * @author Dav__
 */
@Named(value = "userController")
@SessionScoped
public class UserController implements Serializable {

//    @EJB
//    EJBUserLocal user;
    
    @EJB
    AccountManagerLocal accountManager;
    
    private EUser loggedUser;
    
    
    //----- form fields -----
    private String username;
    private String old_password;
    private String password;
    private String conf_password;
    
    
    public UserController() {
    }

    public EUser getLoggedUser(){
        return loggedUser;
    }
    
    public UserTypeEnum getLoggedUserType() {
        if(loggedUser == null){
            return null;
        }
        return loggedUser.getUser_type();
    }

    public String getLoggedName() {
        if(loggedUser == null){
            return null;
        }
        return loggedUser.getName();
    }
    
    public void setLoggedName(String name){
        loggedUser.setName(name);
    }

    public String getLoggedUsername() {
        if(loggedUser == null){
            return null;
        }
        return loggedUser.getUsername();
    }
    
    public void setLoggedUsername(String username){
        loggedUser.setUsername(username);
    }
      
    public String getLoggedAddress(){
        return loggedUser.getAddress();
    }
    
    public void setLoggedAddress(String address){
        loggedUser.setAddress(address);
    }
    
    public UserStatusEnum getLoggedUserStatus(){
        return loggedUser.getStatus();
    }
    
    public Float getLoggedMoney(){
        return loggedUser.getMoney();
    }
    
    public void setLoggedMoney(Float money){
        loggedUser.setMoney(money);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getConf_password() {
        return conf_password;
    }

    public void setConf_password(String conf_password) {
        this.conf_password = conf_password;
    }

    public String getOld_password() {
        return old_password;
    }

    public void setOld_password(String old_password) {
        this.old_password = old_password;
    }
    
    @PostConstruct
    public void postConstruct(){
        this.username = "david";
        this.password = "mercurio26";
        login();
    }
    
    @PreDestroy
    public void preDestroy(){
        logout();
    }
    
    public String login(){
        FacesContext context = FacesContext.getCurrentInstance();
        
        try {
            loggedUser = accountManager.login(username, password);
            username = null;
            password = null;
            return "index";
        } catch (Error403Exception ex) {
            //Logger.getLogger(UserController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        } catch (Error400Exception ex) {
            //Logger.getLogger(UserController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        
        return null;
    }
    
    public String logout(){
        try {
            if(accountManager.logout(loggedUser)){
                loggedUser = null;
                username = null;
                password = null;
                return "/login";
            }
        } catch (Error400Exception ex) {
            Logger.getLogger(UserController.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public String validateUserPermissions(){
        if(loggedUser != null){
            return null;
        }else{
            return "/login";
        }
    }
    
    public String validateAdminPermissions(){
        if(loggedUser != null && loggedUser.getUser_type() == UserTypeEnum.ADMIN){
            return null;
        }else{
            return "/index"; //redirecionar para página de permissões
        }
    }
    
    public void validaPassword(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        
        if(valor.toString().length() < 6){
           FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Password demasiado pequena! Mínimo 6 caracteres!", ""); 
           throw new ValidatorException(fmsg);
        }
        
    }
    
    public String saveUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            if(accountManager.updateUser(loggedUser) != null){
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Alterações guardadas!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        return null;
    }
    
    public String changePassword(){
        FacesContext context = FacesContext.getCurrentInstance();
        
        try {
            if(accountManager.changePassword(loggedUser.getId(), old_password, password, conf_password)){
                 context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Password alterada com sucesso!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        } catch (Error401Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        return null;
    }
    
}

web/templates/pageTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        
        <h:outputScript library="js" name="jquery-3.1.1.min.js" />
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="main.js" />
        
        <h:outputStylesheet library="css" name="bootstrap.css"/>
        <h:outputStylesheet library="css" name="cssLayout.css"/>
         
        <title>TP PD1617 Hugo David 21170208</title>
    </h:head>

    <h:body>

        <div id="header" >
            
            <div class="container">
                
                <div class="logo-container">
                    <div class="col-md-12">
                        <h:link outcome="/index">
                            <h:graphicImage id="img_logo" library="images" name="isec_logo.jpg" height="70px"/>
                        </h:link>

                    </div>
                </div>
                
                <div class="menu-container">  
                    <ul class="menu-nav">
                        <li role="presentation" class="active"><h:link outcome="/index">Newsletter</h:link></li>
                        
                        
                        <h:panelGroup rendered="#{userController.loggedUserType eq 'GUEST' or userController.loggedUserType eq null}">
                            <li role="presentation"><h:link outcome="/lastauctions">Últimos Leilões</h:link></li>
                            <li role="presentation" class="align-right"><h:link outcome="/login">Iniciar Sessão</h:link></li>
                        </h:panelGroup>
                        
                         <h:panelGroup rendered="#{userController.loggedUserType eq 'NORMAL'}">
                            <li role="presentation">
                                <h:link outcome="/user/auctions">Leilões</h:link>
                                <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Leilões</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="#">Em Leilão</h:link></li>
                                    <li><h:link outcome="#">Vendidos</h:link></li>
                                </ul>-->
                            </li>
                            <li role="presentation">
                                <h:link outcome="/user/items">Os Meus Items</h:link>
                                <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Os Meus Items</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="#">Em Leilão</h:link></li>
                                    <li><h:link outcome="#">Vendidos</h:link></li>
                                </ul>-->
                            </li>
                            <li role="presentation">
                                <h:link outcome="/user/messagereceived">Mensagens</h:link>
                                <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Mensagens</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="/user/newmessage">Nova Mensagem</h:link></li>
                                    <li><h:link outcome="/user/messagereceived">Mensagens Recebidas</h:link></li>
                                    <li><h:link outcome="/user/messagesent">Mensagens Enviadas</h:link></li>
                                </ul>-->
                            </li>
                            <li role="presentation" class="dropdown align-right">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >#{userController.loggedName}</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="/user/account">A Minha Conta</h:link></li>
                                    <h:form>
                                         <li><h:commandLink action="#{userController.logout}">Terminar Sessão</h:commandLink></li>
                                    </h:form>
                                    <!--<li role="separator" class="divider"></li>-->
                                </ul>
                            </li>
                            
                        </h:panelGroup>
                        
                        <h:panelGroup rendered="#{userController.loggedUserType eq 'ADMIN'}">
                            <li role="presentation"><h:link outcome="/admin/accounts">Contas</h:link></li>
                            <li role="presentation">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Items</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="/admin/itemlist">Lista de Items</h:link></li>
                                    <li><h:link outcome="/admin/itemcategorieslist">Categorias</h:link></li>
                                </ul>
                            </li>
                            <li role="presentation">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Notificações</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="/admin/userrequests">Pedidos de Utilizadores</h:link></li>
                                    <li><h:link outcome="/admin/reports">Denúncias</h:link></li>
                                </ul>
                            </li>
                            <li role="presentation" class="dropdown align-right">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >#{userController.loggedName}</a>
                                <ul class="dropdown-menu my-dropdown" >
                                    <li><h:link outcome="/user/account">A Minha Conta</h:link></li>
                                    <h:form>
                                         <li><h:commandLink action="#{userController.logout}">Terminar Sessão</h:commandLink></li>
                                    </h:form>
                                    <!--<li role="separator" class="divider"></li>-->
                                </ul>
                            </li>
                        </h:panelGroup>
                    </ul>
                </div>

            </div>
           
        </div>
        <div id="container" >
            
            <div id="content" class="container">
                <h:messages globalOnly="true" class="my-message-list" errorClass="error-list" fatalClass="error-list" infoClass="success-list" />
                <ui:insert name="content" ></ui:insert>
            </div>

        </div>

        <div id="footer" class="container">
            <div class="container">
                <div class="col-md-12">
                    <h5 style="float: right">
                        Hugo David, nº 21170208
                    </h5>
                </div>
            </div>
        </div>
            
    </h:body>

</html>