src/java/ManageBeans/ItemsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.auctions.AuctionsManagerLocal;
import EJB.auctions.ItemCategoriesManagerLocal;
import EJB.auctions.ItemsManagerLocal;
import JPA.EBid;
import JPA.EItem;
import JPA.EItemCategorie;
import JPA.ItemStatusEnum;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.NormalScope;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;
import javax.resource.spi.EISSystemException;

/**
 *
 * @author Dav__
 */
@Named(value = "itemsController")
@SessionScoped
public class ItemsController implements Serializable{

    private Integer offset = 0;
    private Integer numResults = 0;
    
    private EItem item;
    
    private String name;
    private String description;
    private Float initial_price;
    private Float buy_price;
    private Date limit_date;
    private ItemStatusEnum status;
    private Long categorieId;
    
    private Float bid_value;
    
    private static Map<ItemStatusEnum,ItemStatusEnum> itemStatusValues;
    static {
        itemStatusValues = new LinkedHashMap<>();
        itemStatusValues.put(ItemStatusEnum.ONBIDDING, ItemStatusEnum.ONBIDDING);
        itemStatusValues.put(ItemStatusEnum.SOLD, ItemStatusEnum.SOLD);
        itemStatusValues.put(ItemStatusEnum.TIMEOVER, ItemStatusEnum.TIMEOVER);
        itemStatusValues.put(ItemStatusEnum.CANCELED, ItemStatusEnum.CANCELED);
    }
    
    @Inject
    UserController userController;
    
    @EJB
    ItemsManagerLocal itemsManager;
    
    @EJB
    ItemCategoriesManagerLocal itemCategoriesManager;
    
    @EJB
    AuctionsManagerLocal auctionsManager;
    
    public ItemsController() {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String o = params.get("offset");
        
        if(o != null){
            offset = Integer.parseInt(o);
        }else{
            offset = 0;
        }
        
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getNumResults() {
        return numResults;
    }

    public void setNumResults(Integer numResults) {
        this.numResults = numResults;
    }
    
    public Long getItemId(){
        return item.getId();
    }

    public String getItemName() {
        return item.getName();
    }

    public void setItemName(String name) {
        item.setName(name);
    }

    public String getItemDescription() {
        return item.getDescription();
    }

    public void setItemDescription(String description) {
        item.setDescription(description);
    }

    public Float getItemInitial_price() {
        return item.getPrice_initial();
    }

    public void setItemInitial_price(Float initial_price) {
        item.setPrice_initial(initial_price);
    }

    public Float getItemBuy_price() {
        return item.getPrice_buy();
    }

    public void setItemBuy_price(Float buy_price) {
        item.setPrice_buy(buy_price);
    }

    public String getItemLimit_date() {
        return item.getDate_max_bids();
    }
    
    public String getItemOwnerName(){
        return item.getOwner().getName();
    }
    
    public Long getItemOwnerId(){
        return item.getOwner().getId();
    }

    public void setItemLimit_date(String limit_date) {
        FacesContext context = FacesContext.getCurrentInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(limit_date);
        } catch (ParseException ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!", ""));
        }
        item.setDate_max_bids(d);
    }

    public ItemStatusEnum getItemStatus() {
        return item.getStatus();
    }

    public void setItemStatus(ItemStatusEnum status) {
        item.setStatus(status);
    }

    public Long getItemCategorie() {
        return item.getCategorieId().getId();
    }
    
    public String getItemCategorieName() {
        return item.getCategorieId().getName();
    }
    
    public List<EBid> getItemBidsCollection() {
        return (List<EBid>) item.getBidsCollection();
    }

    public void setItemCategorie(Long categorieId) {
        FacesContext context = FacesContext.getCurrentInstance();
        EItemCategorie categorie = null;
        try {
            categorie = itemCategoriesManager.findCategorieById(categorieId);
        } catch (Error400Exception ex) {
            Logger.getLogger(ItemsController.class.getName()).log(Level.SEVERE, null, ex);
        }
        item.setCategorieId(categorie);
    }

    public Map<ItemStatusEnum, ItemStatusEnum> getItemStatusValues() {
        return itemStatusValues;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getInitial_price() {
        return initial_price;
    }

    public void setInitial_price(Float initial_price) {
        this.initial_price = initial_price;
    }

    public Float getBuy_price() {
        return buy_price;
    }

    public void setBuy_price(Float buy_price) {
        this.buy_price = buy_price;
    }

    public String getLimit_date() {
        if(limit_date != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            return sdf.format(limit_date);
        }
        
        return null;
    }

    public void setLimit_date(String limit_date) {
        FacesContext context = FacesContext.getCurrentInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(limit_date);
        } catch (ParseException ex) {
            //Logger.getLogger(ItemsController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!", ""));
        }
        this.limit_date = d;
    }

    public ItemStatusEnum getStatus() {
        return status;
    }

    public void setStatus(ItemStatusEnum status) {
        this.status = status;
    }

    public Long getCategorieId() {
        return categorieId;
    }

    public void setCategorieId(Long categorieId) {
        this.categorieId = categorieId;
    }

    public Float getBid_value() {
        return bid_value;
    }

    public void setBid_value(Float bid_value) {
        this.bid_value = bid_value;
    }

    
    public void validateDate(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(valor.toString());
        } catch (ParseException ex) {
            FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!!", ""); 
            throw new ValidatorException(fmsg);
        }
        
    }
    
    public void validateBidValue(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        Float value = (Float) valor;
        
        List<EBid> bids = getItemBidsCollection();
        
        if(bids != null && bids.size() > 0 ){
            if(bids.get(0).getBid_value() >= value){
                FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "A bid tem que ser superior ao último valor!!", ""); 
                throw new ValidatorException(fmsg);
            }
        }else{
            if(item.getPrice_initial() >= value){
                FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "A bid tem que ser superior ao valor inicial!!", ""); 
                throw new ValidatorException(fmsg);
            }
        }
    }
    
    public String findItem(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id!=null){
            try {
                item = itemsManager.findItembyId(Long.parseLong(id));
            } catch (Error400Exception ex) {
                //Logger.getLogger(ItemCategoriesController.class.getName()).log(Level.SEVERE, null, ex);
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
            }
        }
        
        return null;
    }
    
    public String findItemOwnedByUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id!=null){
            try {
                item = itemsManager.findItemByIdByUser(Long.parseLong(id), userController.getLoggedUser().getId());
                
                if(item == null){

src/java/ManageBeans/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.Exceptions.Error401Exception;
import EJB.Exceptions.Error403Exception;
import EJB.account.AccountManagerLocal;
import JPA.UserTypeEnum;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import JPA.EUser;
import JPA.UserStatusEnum;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

/**
 *
 * @author Dav__
 */
@Named(value = "userController")
@SessionScoped
public class UserController implements Serializable {

//    @EJB
//    EJBUserLocal user;
    
    @EJB
    AccountManagerLocal accountManager;
    
    private EUser loggedUser;
    
    
    //----- form fields -----
    private String username;
    private String old_password;
    private String password;
    private String conf_password;
    
    
    public UserController() {
    }

    public EUser getLoggedUser(){
        return loggedUser;
    }
    
    public UserTypeEnum getLoggedUserType() {
        if(loggedUser == null){
            return null;
        }
        return loggedUser.getUser_type();
    }

    public String getLoggedName() {
        if(loggedUser == null){
            return null;
        }
        return loggedUser.getName();
    }
    
    public void setLoggedName(String name){
        loggedUser.setName(name);
    }

    public String getLoggedUsername() {
        if(loggedUser == null){
            return null;
        }
        return loggedUser.getUsername();
    }
    
    public void setLoggedUsername(String username){
        loggedUser.setUsername(username);
    }
      
    public String getLoggedAddress(){
        return loggedUser.getAddress();
    }
    
    public void setLoggedAddress(String address){
        loggedUser.setAddress(address);
    }
    
    public UserStatusEnum getLoggedUserStatus(){
        return loggedUser.getStatus();
    }
    
    public Float getLoggedMoney(){
        return loggedUser.getMoney();
    }
    
    public void setLoggedMoney(Float money){
        loggedUser.setMoney(money);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getConf_password() {
        return conf_password;
    }

    public void setConf_password(String conf_password) {
        this.conf_password = conf_password;
    }

    public String getOld_password() {
        return old_password;
    }

    public void setOld_password(String old_password) {
        this.old_password = old_password;
    }
    
    @PostConstruct
    public void postConstruct(){
        this.username = "david";
        this.password = "mercurio26";
        login();
    }
    
    @PreDestroy
    public void preDestroy(){
        logout();
    }
    
    public String login(){
        FacesContext context = FacesContext.getCurrentInstance();
        
        try {
            loggedUser = accountManager.login(username, password);
            username = null;
            password = null;
            return "index";
        } catch (Error403Exception ex) {
            //Logger.getLogger(UserController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        } catch (Error400Exception ex) {
            //Logger.getLogger(UserController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        
        return null;
    }
    
    public String logout(){
        try {
            if(accountManager.logout(loggedUser)){
                loggedUser = null;
                username = null;
                password = null;
                return "/login";
            }
        } catch (Error400Exception ex) {
            Logger.getLogger(UserController.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public String validateUserPermissions(){
        if(loggedUser != null){
            return null;
        }else{
            return "/login";
        }
    }
    
    public String validateAdminPermissions(){
        if(loggedUser != null && loggedUser.getUser_type() == UserTypeEnum.ADMIN){
            return null;
        }else{
            return "/index"; //redirecionar para página de permissões
        }
    }
    
    public void validaPassword(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        
        if(valor.toString().length() < 6){
           FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Password demasiado pequena! Mínimo 6 caracteres!", ""); 
           throw new ValidatorException(fmsg);
        }
        
    }
    
    public String saveUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            if(accountManager.updateUser(loggedUser) != null){
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Alterações guardadas!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        
        return null;
    }
    
    public String changePassword(){
        FacesContext context = FacesContext.getCurrentInstance();
        
        try {
            if(accountManager.changePassword(loggedUser.getId(), old_password, password, conf_password)){
                 context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Password alterada com sucesso!", ""));
            }
        } catch (Error400Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        } catch (Error401Exception ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
        }
        return null;
    }
    
}

web/user/item.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <f:metadata >
        <f:viewAction action="#{userController.validateUserPermissions}" />
        <f:viewAction action="#{itemsController.findItem}" />
    </f:metadata>
    
    <ui:define name="content">
        
        <h:panelGroup layout="block" class="col-md-9">
            <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Item #{itemsController.itemName}</h:outputLabel>
                </h:panelGroup>
                
                <h:panelGroup layout="block" class="panel-body">
                    
                    <h:panelGroup layout="block" class="col-md-8" style="margin-bottom: 5px">
                        <h:outputLabel value="Name:" for="name" />
                        <h:outputText value="&nbsp;#{itemsController.itemName}" />
                    </h:panelGroup>
                    
                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Utilizador:" for="name" />
                        <h:link outcome="/user/viewuser?id=#{itemsController.itemOwnerId}"><h:outputText value="&nbsp;#{itemsController.itemOwnerName}" /></h:link>
                    </h:panelGroup>
                    
                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Categoria:" for="categorie" />
                        <h:outputText value="&nbsp;#{itemsController.itemCategorieName}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Preço inicial:" for="init_price" />
                        <h:outputText value="&nbsp;#{itemsController.itemInitial_price}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Preço de Compra:" for="buy_price" />
                        <h:outputText value="&nbsp;#{itemsController.itemBuy_price}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-8" style="margin-bottom: 5px">
                        <h:outputLabel value="Descrição:" for="description" />
                        <h:outputText value="&nbsp;#{itemsController.itemDescription}" />
                    </h:panelGroup>
                    
                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Data Limite (yyyy/mm/dd):" for="limit_date" />
                        <h:outputText value="&nbsp;#{itemsController.itemLimit_date}" />
                    </h:panelGroup>

                    <h:form rendered="#{itemsController.itemStatus eq 'ONBIDDING' and itemsController.itemOwnerId ne userController.loggedUser.id}" > 
                        
                        <h:panelGroup layout="block" class="col-md-12" style="margin-top: 10px; "> 

                            <h:commandButton class="btn btn-primary" style="float: right; margin-left: 10px" action="#{itemsController.bidItem}" value="Bid"/> 
                            
                            <h:panelGroup layout="block" class="col-md-3" style=" margin: 0; padding: 0; float: right">
                                <h:inputText id="bid"  validator="#{itemsController.validateBidValue}" class="form-control my-input" required="true" value="#{itemsController.bid_value}" requiredMessage="Introduza um valor para a bid!" />
                                <h:messages for="bid" class="my-message-list error-list"  />
                            </h:panelGroup>

                        </h:panelGroup>
                    </h:form>
                    
                    <h:form rendered="#{itemsController.itemStatus eq 'ONBIDDING' and itemsController.itemOwnerId ne userController.loggedUser.id}" > 
                        <h:panelGroup layout="block" class="col-md-12" style="margin-top: 10px" >

                            <h:commandButton class="btn btn-success" style="float: right; margin-left: 10px" action="#{itemsController.buyItem}" value="Comprar"/>
                            
                            <h:link outcome="/user/reportitem?id=#{itemsController.itemId}" class="btn btn-warning" style="float: left;">Denunciar</h:link>
                            
                        </h:panelGroup>
                    </h:form>
                    
                    <h:panelGroup layout="block" class="col-md-12" style="margin-top: 20px">
                        <h:panelGroup layout="block" class="panel panel-default">
                            <h:panelGroup layout="block" class="panel-heading">
                                <h:outputLabel class="h3 panel-title">Lista de bids</h:outputLabel>
                            </h:panelGroup>

                            <h:panelGroup layout="block" class="panel-body">
                                
                                <h:dataTable value="#{itemsController.itemBidsCollection}" var="bid" cellpadding="0" cellspacing="0"
                                 rules="all" class="table table-responsive table-hover" >
                        
                                    <h:column  >
                                       <f:facet name="header">
                                           <h:outputText value="Utilizador"/>
                                       </f:facet>
                                        <h:outputText value="#{bid.userId.name}"/>
                                    </h:column>
                                    
                                    <h:column  >
                                       <f:facet name="header">
                                           <h:outputText value="Valor"/>
                                       </f:facet>
                                        <h:outputText value="#{bid.bid_value}"/>
                                    </h:column>
                                    
                                    <h:column  >
                                       <f:facet name="header">
                                           <h:outputText value="Data"/>
                                       </f:facet>
                                        <h:outputText value="#{bid.createdAt}"/>
                                    </h:column>

                                </h:dataTable>
                                
                            </h:panelGroup>
                
                        </h:panelGroup>
                        
                    </h:panelGroup>
                    
                </h:panelGroup>
                
            </h:panelGroup>
        </h:panelGroup>
        
        <h:panelGroup layout="block" class="col-md-3">
            <h:panelGroup layout="block" class="list-group">
                <h:link outcome="/user/items" class="list-group-item">Os Meus Items</h:link>
                <h:link outcome="/user/boughtitems" class="list-group-item">Items Comprados</h:link>
            </h:panelGroup>
        </h:panelGroup>
        
    </ui:define>


</ui:composition>

web/user/ownitem.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <f:metadata >
        <f:viewAction action="#{userController.validateUserPermissions}" />
        <f:viewAction action="#{itemsController.findItemOwnedByUser}" />
    </f:metadata>
    
    <ui:define name="content">
        
        <h:panelGroup layout="block" class="col-md-9">
            <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Item #{itemsController.itemName}</h:outputLabel>
                </h:panelGroup>
                
                <h:panelGroup layout="block" class="panel-body">
                    
                   
                    <h:panelGroup layout="block" class="col-md-8" style="margin-bottom: 5px">
                        <h:outputLabel value="Name:" for="name" />
                        <h:outputText value="&nbsp;#{itemsController.itemName}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Categoria:" for="categorie" />
                        <h:outputText value="&nbsp;#{itemsController.itemCategorieName}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Preço inicial:" for="init_price" />
                        <h:outputText value="&nbsp;#{itemsController.itemInitial_price}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Preço de Compra:" for="buy_price" />
                        <h:outputText value="&nbsp;#{itemsController.itemBuy_price}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Estado:" for="status" />
                        <h:outputText value="&nbsp;#{itemsController.itemStatus}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-8" style="margin-bottom: 5px">
                        <h:outputLabel value="Descrição:" for="description" />
                        <h:outputText value="&nbsp;#{itemsController.itemDescription}" />
                    </h:panelGroup>

                    <h:panelGroup layout="block" class="col-md-4" style="margin-bottom: 5px">
                        <h:outputLabel value="Data Limite (yyyy/mm/dd):" for="limit_date" />
                        <h:outputText value="&nbsp;#{itemsController.itemLimit_date}" />
                    </h:panelGroup>

                    <h:form > 
                        <h:panelGroup layout="block" class="col-md-12">
                            <h:commandButton rendered="#{itemsController.itemStatus eq 'ONBIDDING'}"
                                             class="btn btn-warning" style="float: right" action="#{itemsController.cancelOwnItem}" value="Cancelar Item"/>
                        </h:panelGroup>
                    </h:form>
                    
                    <h:panelGroup layout="block" class="col-md-12" style="margin-top: 20px">
                        <h:panelGroup layout="block" class="panel panel-default">
                            <h:panelGroup layout="block" class="panel-heading">
                                <h:outputLabel class="h3 panel-title">Lista de bids</h:outputLabel>
                            </h:panelGroup>

                            <h:panelGroup layout="block" class="panel-body">
                                
                                <h:dataTable value="#{itemsController.itemBidsCollection}" var="bid" cellpadding="0" cellspacing="0"
                                 rules="all" class="table table-responsive table-hover" >
                        
                                    <h:column  >
                                       <f:facet name="header">
                                           <h:outputText value="Utilizador"/>
                                       </f:facet>
                                        <h:outputText value="#{bid.userId.name}"/>
                                    </h:column>
                                    
                                    <h:column  >
                                       <f:facet name="header">
                                           <h:outputText value="Valor"/>
                                       </f:facet>
                                        <h:outputText value="#{bid.bid_value}"/>
                                    </h:column>
                                    
                                    <h:column  >
                                       <f:facet name="header">
                                           <h:outputText value="Data"/>
                                       </f:facet>
                                        <h:outputText value="#{bid.createdAt}"/>
                                    </h:column>

                                </h:dataTable>
                                
                            </h:panelGroup>
                
                        </h:panelGroup>
                        
                    </h:panelGroup>

                </h:panelGroup>
                
            </h:panelGroup>
        </h:panelGroup>
        
        <h:panelGroup layout="block" class="col-md-3">
            <h:panelGroup layout="block" class="list-group">
                <h:link outcome="/user/items" class="list-group-item">Os Meus Items</h:link>
                <h:link outcome="/user/boughtitems" class="list-group-item">Items Comprados</h:link>
            </h:panelGroup>
        </h:panelGroup>
        
    </ui:define>


</ui:composition>