src/java/ManageBeans/ItemsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.auctions.AuctionsManagerLocal;
import EJB.auctions.ItemCategoriesManagerLocal;
import EJB.auctions.ItemsManagerLocal;
import JPA.EBid;
import JPA.EItem;
import JPA.EItemCategorie;
import JPA.ItemStatusEnum;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.NormalScope;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;
import javax.resource.spi.EISSystemException;

/**
 *
 * @author Dav__
 */
@Named(value = "itemsController")
@SessionScoped
public class ItemsController implements Serializable{

    private Integer offset = 0;
    private Integer numResults = 0;
    
    private EItem item;
    
    private String name;
    private String description;
    private Float initial_price;
    private Float buy_price;
    private Date limit_date;
    private ItemStatusEnum status;
    private Long categorieId;
    
    private Float bid_value;
    
    private static Map<ItemStatusEnum,ItemStatusEnum> itemStatusValues;
    static {
        itemStatusValues = new LinkedHashMap<>();
        itemStatusValues.put(ItemStatusEnum.ONBIDDING, ItemStatusEnum.ONBIDDING);
        itemStatusValues.put(ItemStatusEnum.SOLD, ItemStatusEnum.SOLD);
        itemStatusValues.put(ItemStatusEnum.TIMEOVER, ItemStatusEnum.TIMEOVER);
        itemStatusValues.put(ItemStatusEnum.CANCELED, ItemStatusEnum.CANCELED);
    }
    
    @Inject
    UserController userController;
    
    @EJB
    ItemsManagerLocal itemsManager;
    
    @EJB
    ItemCategoriesManagerLocal itemCategoriesManager;
    
    @EJB
    AuctionsManagerLocal auctionsManager;
    
    public ItemsController() {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String o = params.get("offset");
        
        if(o != null){
            offset = Integer.parseInt(o);
        }else{
            offset = 0;
        }
        
    }

    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getNumResults() {
        return numResults;
    }

    public void setNumResults(Integer numResults) {
        this.numResults = numResults;
    }
    
    public Long getItemId(){
        return item.getId();
    }

    public String getItemName() {
        return item.getName();
    }

    public void setItemName(String name) {
        item.setName(name);
    }

    public String getItemDescription() {
        return item.getDescription();
    }

    public void setItemDescription(String description) {
        item.setDescription(description);
    }

    public Float getItemInitial_price() {
        return item.getPrice_initial();
    }

    public void setItemInitial_price(Float initial_price) {
        item.setPrice_initial(initial_price);
    }

    public Float getItemBuy_price() {
        return item.getPrice_buy();
    }

    public void setItemBuy_price(Float buy_price) {
        item.setPrice_buy(buy_price);
    }

    public String getItemLimit_date() {
        return item.getDate_max_bids();
    }
    
    public String getItemOwnerName(){
        return item.getOwner().getName();
    }
    
    public Long getItemOwnerId(){
        return item.getOwner().getId();
    }

    public void setItemLimit_date(String limit_date) {
        FacesContext context = FacesContext.getCurrentInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(limit_date);
        } catch (ParseException ex) {
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!", ""));
        }
        item.setDate_max_bids(d);
    }

    public ItemStatusEnum getItemStatus() {
        return item.getStatus();
    }

    public void setItemStatus(ItemStatusEnum status) {
        item.setStatus(status);
    }

    public Long getItemCategorie() {
        return item.getCategorieId().getId();
    }
    
    public String getItemCategorieName() {
        return item.getCategorieId().getName();
    }
    
    public List<EBid> getItemBidsCollection() {
        return (List<EBid>) item.getBidsCollection();
    }

    public void setItemCategorie(Long categorieId) {
        FacesContext context = FacesContext.getCurrentInstance();
        EItemCategorie categorie = null;
        try {
            categorie = itemCategoriesManager.findCategorieById(categorieId);
        } catch (Error400Exception ex) {
            Logger.getLogger(ItemsController.class.getName()).log(Level.SEVERE, null, ex);
        }
        item.setCategorieId(categorie);
    }

    public Map<ItemStatusEnum, ItemStatusEnum> getItemStatusValues() {
        return itemStatusValues;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getInitial_price() {
        return initial_price;
    }

    public void setInitial_price(Float initial_price) {
        this.initial_price = initial_price;
    }

    public Float getBuy_price() {
        return buy_price;
    }

    public void setBuy_price(Float buy_price) {
        this.buy_price = buy_price;
    }

    public String getLimit_date() {
        if(limit_date != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            return sdf.format(limit_date);
        }
        
        return null;
    }

    public void setLimit_date(String limit_date) {
        FacesContext context = FacesContext.getCurrentInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(limit_date);
        } catch (ParseException ex) {
            //Logger.getLogger(ItemsController.class.getName()).log(Level.SEVERE, null, ex);
            context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!", ""));
        }
        this.limit_date = d;
    }

    public ItemStatusEnum getStatus() {
        return status;
    }

    public void setStatus(ItemStatusEnum status) {
        this.status = status;
    }

    public Long getCategorieId() {
        return categorieId;
    }

    public void setCategorieId(Long categorieId) {
        this.categorieId = categorieId;
    }

    public Float getBid_value() {
        return bid_value;
    }

    public void setBid_value(Float bid_value) {
        this.bid_value = bid_value;
    }

    
    public void validateDate(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = null;
        try {
            d = sdf.parse(valor.toString());
        } catch (ParseException ex) {
            FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Data inválida!!", ""); 
            throw new ValidatorException(fmsg);
        }
        
    }
    
    public void validateBidValue(FacesContext fc, UIComponent uic, Object valor) throws ValidatorException{
        Float value = (Float) valor;
        
        List<EBid> bids = getItemBidsCollection();
        
        if(bids != null && bids.size() > 0 ){
            if(bids.get(0).getBid_value() >= value){
                FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "A bid tem que ser superior ao último valor!!", ""); 
                throw new ValidatorException(fmsg);
            }
        }else{
            if(item.getPrice_initial() >= value){
                FacesMessage fmsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "A bid tem que ser superior ao valor inicial!!", ""); 
                throw new ValidatorException(fmsg);
            }
        }
    }
    
    public String findItem(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id!=null){
            try {
                item = itemsManager.findItembyId(Long.parseLong(id));
            } catch (Error400Exception ex) {
                //Logger.getLogger(ItemCategoriesController.class.getName()).log(Level.SEVERE, null, ex);
                context.addMessage( null, new FacesMessage(FacesMessage.SEVERITY_ERROR, ex.getMessage(), ""));
            }
        }
        
        return null;
    }
    
    public String findItemOwnedByUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String id = params.get("id");
        
        if(id!=null){
            try {
                item = itemsManager.findItemByIdByUser(Long.parseLong(id), userController.getLoggedUser().getId());
                
                if(item == null){

src/java/ManageBeans/NewsletterController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.newsletter.NewsletterManagerLocal;
import JPA.ENewsletter;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Dav__
 */
@Named(value = "newsletterController")
@RequestScoped
public class NewsletterController {
    
    private Integer offset = 0;
    private Integer numResults = 0;
    
    @EJB
    NewsletterManagerLocal newsletterManager;

    public NewsletterController() {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String o = params.get("offset");
        
        if(o != null){
            offset = Integer.parseInt(o);
        }else{
            offset = 0;
        }
        
    }
    
    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }
    
    public Integer getNumResults() {
        return numResults;
    }

    public void setNumResults(Integer numResults) {
        this.numResults = numResults;
    }
    
    public List<ENewsletter> getLastNewsletterItems(){
        if(offset == null || offset < 0){
            offset = 0;
        }
        
        List<ENewsletter> news = newsletterManager.getLastNewsletterItems(offset);
        this.numResults = news.size();
        return news;
    }
}

src/java/ManageBeans/TransactionsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManageBeans;

import EJB.Exceptions.Error400Exception;
import EJB.auctions.TransactionManagerLocal;
import JPA.EItem;
import JPA.ETransaction;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Dav__
 */
@Named(value = "transactionsController")
@RequestScoped
public class TransactionsController {

    @EJB
    TransactionManagerLocal transactionManager;
    
    @Inject
    UserController userController;
    
    private Integer offset = 0;
    private Integer numResults = 0;
    
    public TransactionsController() {
        
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> params = context.getExternalContext().getRequestParameterMap();
        String o = params.get("offset");
        
        if(o != null){
            offset = Integer.parseInt(o);
        }else{
            offset = 0;
        }
        
    }
    
    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getNumResults() {
        return numResults;
    }

    public void setNumResults(Integer numResults) {
        this.numResults = numResults;
    }
    
    public List<ETransaction> getAllItemsByUser(){
        FacesContext context = FacesContext.getCurrentInstance();
        
        if(offset == null || offset < 0){
            offset = 0;
        }

        List<ETransaction> transactions = transactionManager.getAllTransactionsByUser(userController.getLoggedUser().getId(), offset);
        this.numResults = transactions.size();
        return transactions;

    }
    
    public List<ETransaction> getLastItems(){
        FacesContext context = FacesContext.getCurrentInstance();

        List<ETransaction> transactions = transactionManager.getLastTransactions();
        this.numResults = transactions.size();
        
        return transactions;

    }
}

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">


    <ui:define name="content">
        <h:panelGroup layout="block" class="col-md-12">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Newsletter</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    
                    
                    <h:dataTable value="#{newsletterController.lastNewsletterItems}" var="item" cellpadding="0" cellspacing="0"
                                 rules="all" class="table table-responsive table-hover" >
                        <!--<h:column  >
                           <f:facet name="header">
                               <h:outputText value="ID"/>
                           </f:facet>
                            <h:outputText value="#{item.id}"/>
                       </h:column>-->
                        <h:column  >
                           <f:facet name="header">
                               <h:outputText value="Mensagem"/>
                           </f:facet>
                            <h:outputText value="#{item.message}"/>
                       </h:column>
                        <h:column >
                           <f:facet name="header">
                               <h:outputText value="Data de Criação"/>
                           </f:facet>
                           <h:outputText value="#{item.createdAt}"/>
                       </h:column>
                   </h:dataTable>
                    
                    <h:panelGroup layout="block" class="col-md-12" >
                        
                        <h:form>
                            
                            <h:link style="float: left" rendered="#{newsletterController.offset ge 10}" outcome="/index?offset=#{newsletterController.offset - 10}">
                                <h:panelGroup class="glyphicon glyphicon-chevron-left"></h:panelGroup> Anterior
                            </h:link>
                            
                            <h:link style="float: right" rendered="#{newsletterController.numResults eq 10}" outcome="/index?offset=#{newsletterController.offset + 10}">
                                Próximo <h:panelGroup class="glyphicon glyphicon-chevron-right"></h:panelGroup>
                            </h:link>
                            
                        </h:form>
                        
                    </h:panelGroup>
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
        <!--<h:panelGroup layout="block" class="col-md-3">
            <h:panelGroup layout="block" class="list-group">
                <h:link outcome="/index" class="list-group-item">Dapibus ac facilisis in</h:link>
                <h:link outcome="/index" class="list-group-item">Morbi leo risus</h:link>
                <h:link outcome="/index" class="list-group-item">Porta ac consectetur ac</h:link>
                <h:link outcome="/index" class="list-group-item">Vestibulum at eros</h:link>
            </h:panelGroup>
        </h:panelGroup>-->
    </ui:define>
    
</ui:composition>

web/lastauctions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="content">
        
        <h:panelGroup layout="block" class="col-md-12">
            <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Últimos Leilões</h:outputLabel>
                </h:panelGroup>
                
                <h:panelGroup layout="block" class="panel-body">
                    
                    <h:panelGroup layout="block" class="panel-body">
                    
                        <h:dataTable value="#{transactionsController.lastItems}" var="transaction" cellpadding="0" cellspacing="0"
                                 rules="all" class="table table-responsive table-hover" >
                        
                        <h:column  >
                           <f:facet name="header">
                               <h:outputText value="Item"/>
                           </f:facet>
                            <h:outputText value="#{transaction.userId.name}"/>
                        </h:column>
                            
                        <h:column  >
                           <f:facet name="header">
                               <h:outputText value="Item"/>
                           </f:facet>
                                <h:outputText value="#{transaction.itemId.name}"/>
                        </h:column>
                        
                        <h:column  >
                            <f:facet name="header">
                                <h:outputText value="Valor"/>
                            </f:facet>
                            <h:outputText value="#{transaction.transaction_value}"/>
                            
                        </h:column>
                        
                        <h:column  >
                            <f:facet name="header">
                                <h:outputText value="Data"/>
                            </f:facet>
                            <h:outputText value="#{transaction.createdAt}"/>
                            
                        </h:column>
                        
                        
                    </h:dataTable>
                    
                </h:panelGroup>
                    
                </h:panelGroup>
                
            </h:panelGroup>
        </h:panelGroup>
        
    </ui:define>

</ui:composition>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns="http://www.w3.org/1999/xhtml">

    <ui:define name="content">
        <h:panelGroup layout="block" class="col-md-9">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Iniciar Sessão</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    <h:panelGroup layout="block" class="col-md-12">
                        <h:form >
                            <h:outputLabel value="Username" for="username" />
                            <h:inputText id="username" class="form-control my-input" required="true" value="#{userController.username}" requiredMessage="Introduza o username" />
                            <h:messages for="username" class="my-message-list error-list"  />
                            <h:outputLabel value="Password" for="password" />
                            <h:inputSecret id="password"  class="form-control my-input" required="true" value="#{userController.password}" requiredMessage="Introduza a password" />
                            <h:messages for="password" class="my-message-list error-list"  />

                            <h:commandButton id="login_button" class="btn btn-success" style="float: right" action="#{userController.login}" value="Iniciar Sessão" />

                        </h:form>
                    </h:panelGroup>
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
        <h:panelGroup layout="block" class="col-md-3">
            <h:panelGroup layout="block" class="list-group">
                <h:link outcome="/requestaccess" class="list-group-item">Registar Conta</h:link>
                <h:link outcome="/reativateaccount" class="list-group-item">Pedir reativação de conta</h:link>
            </h:panelGroup>
        </h:panelGroup>
    </ui:define>

</ui:composition>

web/reativateaccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="content">
        <h:panelGroup layout="block" class="col-md-9">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Reativar Conta</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    <h:panelGroup layout="block" class="col-md-12">
                        <h:form >
                            <h:outputLabel value="Username" for="username" />
                            <h:inputText id="username" class="form-control my-input" required="true" value="#{requestsController.username}" requiredMessage="Introduza o username" />
                            <h:messages for="username" class="my-message-list error-list"  />

                            <h:commandButton class="btn btn-success" style="float: right" action="#{requestsController.reactivateAcount}" value="Efetuar Pedido" />

                        </h:form>
                    </h:panelGroup>
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
        <h:panelGroup layout="block" class="col-md-3">
            <h:panelGroup layout="block" class="list-group">
                <h:link outcome="/login" class="list-group-item">Iniciar Sessão</h:link>
                <h:link outcome="/requestaccess" class="list-group-item">Registar Conta</h:link>
            </h:panelGroup>
        </h:panelGroup>
    </ui:define>

</ui:composition>

web/requestaccess.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/templates/pageTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="content">
        <h:panelGroup layout="block" class="col-md-9">
             <h:panelGroup layout="block" class="panel panel-default">
                <h:panelGroup layout="block" class="panel-heading">
                    <h:outputLabel class="h3 panel-title">Registar Conta</h:outputLabel>
                </h:panelGroup>
                <h:panelGroup layout="block" class="panel-body">
                    
                    <h:panelGroup layout="block" class="col-md-12">
                        <h:form >
                            <h:outputLabel value="Name" for="name" />
                            <h:inputText id="name" class="form-control my-input" required="true" value="#{requestsController.name}" requiredMessage="Introduza o nome" />
                            <h:messages for="name" class="my-message-list error-list"  />

                            <h:outputLabel value="Endereço" for="address" />
                            <h:inputText id="address" class="form-control my-input" required="false" value="#{requestsController.address}" />
                            <h:messages for="address" class="my-message-list error-list"  />

                            <h:outputLabel value="Username" for="username" />
                            <h:inputText id="username" class="form-control my-input" required="true" value="#{requestsController.username}" requiredMessage="Introduza o username" />
                            <h:messages for="username" class="my-message-list error-list"  />

                            <h:outputLabel value="Password" for="password" />
                            <h:inputSecret id="password" class="form-control my-input" required="true" value="#{requestsController.password}" requiredMessage="Introduza a password" />
                            <h:messages for="password" class="my-message-list error-list"  />

                            <h:outputLabel value="Confirme a Password" for="conf_password" />
                            <h:inputSecret id="conf_password" class="form-control my-input" required="true" value="#{requestsController.conf_password}" validator="#{requestsController.validaPassword}" requiredMessage="Confirme a password" />
                            <h:messages for="conf_password" class="my-message-list error-list"  />

                            <h:commandButton class="btn btn-success" style="float: right" action="#{requestsController.requestAccess}" value="Efetuar Pedido" />

                        </h:form>
                    </h:panelGroup>
                    
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>
        
        <h:panelGroup layout="block" class="col-md-3">
            <h:panelGroup layout="block" class="list-group">
                <h:link outcome="/login" class="list-group-item">Iniciar Sessão</h:link>
                <h:link outcome="/reativateaccount" class="list-group-item">Pedir reativação de conta</h:link>
                
            </h:panelGroup>
        </h:panelGroup>
    </ui:define>

</ui:composition>